version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run: apt-get -qq update && apt-get -qq install git curl wget
      - run: git clone https://github.com/XiaomiFirmwareUpdater/miui-updates-tracker.git -b weekly_fastboot $HOME/project/
      - run: cd $HOME/project/
      - run: chmod 775 *.sh
      - run: ./weekly_fastboot.sh

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
  weekly_fastboot:
    triggers:
      - schedule:
          cron: "5 10 * * 5"
          filters:
            branches:
              only: weekly_fastboot

    jobs:
      - build
